### ISSUE TITLE
already installed playwright

### ISSUE THREAD

**Issue by Jacck** [Automata-Labs-team/MCP-Server-Playwright#2]
I got the following error after installation of MCP playwright server, when prompting Claude, in Claude desktop:
![playwright error](https://github.com/user-attachments/assets/da0bbef9-e962-4190-a204-28f0914eaa34)

**Comment by VikashLoomba** [comment]
If you run the box command given in the error, it should install the required playwright browsers so that it can launch correctly. On Dec 5, 2024, at 4:10 PM, Jacck ***@***.***> wrote:﻿
I got the following error after installation of MCP playwright server, when prompting Claude, in Claude desktop:
playwright.error.png (view on web)

**Comment by Jacck** [comment]
it works, thx
